apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: auto-go0328
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: auto-go0328 
  name: auto-go0328
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: auto-go0328
    weight: 100 
